#! /bin/sh
# /etc/init.d/ibeacon-detector

### BEGIN INIT INFO
# Provides:          ibeacon-detector
# Required-Start:    $all
# X-UnitedLinux-Should-Start:
# Required-Stop:     $all
# X-UnitedLinux-Should-Stop:
# User:              root
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: iBeacon Detector autostart
# Description:       iBeacon Detector app (https://github.com/dluxemburg/ibeacon-detector) autostart, thanks to http://www.stuffaboutcode.com/2012/06/raspberry-pi-run-program-at-start-up.html
### END INIT INFO


export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
export HOME=/root

case "$1" in
  start)
    echo "Starting iBeacon detector node app"
    /usr/local/bin/hciconfig hci0 up
    /usr/local/bin/forever start -al /var/log/forever.log -o /var/log/ibeacon-detector.log -e /var/log/ibeacon-detector-error.log sourceDir=/usr/local/ibeacon-detector index.js
    ;;
  stop)
    echo "Stopping all Forever processes"
    exec /usr/local/bin/forever stopall
    ;;
  *)
    echo "Usage: /etc/init.d/ibeacon-detector {start|stop}"
    exit 1
    ;;
esac

exit 0