#! /bin/sh
# /etc/init.d/ibeacon-detector

### BEGIN INIT INFO
# Provides:          ibeacon-detector
# Required-Start:    $all
# Required-Stop:     $all
# User:              root
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: iBeacon Detector autostart
# Description:       iBeacon Detector app (https://github.com/dluxemburg/ibeacon-detector) autostart, thanks to http://www.stuffaboutcode.com/2012/06/raspberry-pi-run-program-at-start-up.html
### END INIT INFO

case "$1" in
  start)
    echo "Starting iBeacon detector node app"
    hciconfig hci0 up
    sh /usr/local/ibeacon-detector/start
    ;;
  stop)
    echo "Stopping all node processes"
    killall node
    ;;
  *)
    echo "Usage: /etc/init.d/ibeacon-detector {start|stop}"
    exit 1
    ;;
esac

exit 0